# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f02cf1cc12c81f3f6d50b99cf8b58f39367968d070953a6c7d1af1956c1d14c0
# To regenerate: alef e2e generate
# To verify freshness: alef verify
# E2e tests for category: pdf
defmodule E2e.PdfTest do
  use ExUnit.Case, async: false

  describe "pdf_page_count_invalid" do
    test "pdf_page_count_invalid" do
      assert {:error, _} = Xberg.pdf_page_count("this is not a pdf document")
    end
  end

  describe "pdf_page_count_valid" do
    test "pdf_page_count_valid" do
      pdf_bytes = :binary.bin_to_list(File.read!("../../test_documents/pdf/sample_contract.pdf"))
      {:ok, result} = Xberg.pdf_page_count(pdf_bytes)
      assert result == 10
    end
  end
end
