# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e896903741c8f6b1dcf4bb7d8b716f8f561f7050569e0d32167fe005d2c4c678
# To regenerate: alef e2e generate
# To verify freshness: alef verify
# E2e tests for category: pdf
defmodule E2e.PdfTest do
  use ExUnit.Case, async: false

  describe "pdf_page_count_invalid" do
    test "pdf_page_count_invalid" do
      pdf_bytes = :binary.bin_to_list(File.read!("../../test_documents/text/plain.txt"))
      assert {:error, _} = Xberg.pdf_page_count(pdf_bytes)
    end
  end

  describe "pdf_page_count_password" do
    test "pdf_page_count_password" do
      pdf_bytes = :binary.bin_to_list(File.read!("../../test_documents/pdf/password_protected.pdf"))
      {:ok, result} = Xberg.pdf_page_count(pdf_bytes, password: "")
      assert result == 2
    end
  end

  describe "pdf_page_count_valid" do
    test "pdf_page_count_valid" do
      pdf_bytes = :binary.bin_to_list(File.read!("../../test_documents/pdf/sample_contract.pdf"))
      {:ok, result} = Xberg.pdf_page_count(pdf_bytes)
      assert result == 10
    end
  end
end
