// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e5058e60d32cca37fda5af49f74378575a8d34fdcfff6d63a17ed6e2c291e771
// To regenerate: alef e2e generate
// To verify freshness: alef verify

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Xberg;
using static Xberg.XbergConverter;

namespace Xberg
{
    /// <summary>E2e tests for category: pdf.</summary>
    public class PdfTests
    {
            private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

        [Fact]
        public void Test_PdfPageCountInvalid()
        {
            // pdf_page_count: bytes that are not a PDF
            Assert.ThrowsAny<XbergException>(() =>
            {
                XbergConverter.PdfPageCount(System.Text.Encoding.UTF8.GetBytes("this is not a pdf document"), null);
            });
        }

        [Fact]
        public void Test_PdfPageCountValid()
        {
            // pdf_page_count: page count of a multi-page PDF
            var result = XbergConverter.PdfPageCount(System.IO.File.ReadAllBytes("pdf/sample_contract.pdf"), null);
            Assert.True(result == 10);

        }


    }
}
