// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a8488094ead8c13881db804316152f5dccb410f102ec02c61b5d7eaaa2649a32
// To regenerate: alef e2e generate
// To verify freshness: alef verify

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Xberg;
using static Xberg.XbergConverter;

namespace Xberg
{
    /// <summary>E2e tests for category: pdf.</summary>
    public class PdfTests
    {
            private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

        [Fact]
        public void Test_PdfPageCountInvalid()
        {
            // pdf_page_count: a plain text file is not a PDF
            Assert.ThrowsAny<XbergException>(() =>
            {
                XbergConverter.PdfPageCount(System.IO.File.ReadAllBytes("text/plain.txt"), null);
            });
        }

        [Fact]
        public void Test_PdfPageCountPassword()
        {
            // pdf_page_count: encrypted PDF opened with its user password
            var result = XbergConverter.PdfPageCount(System.IO.File.ReadAllBytes("pdf/password_protected.pdf"), "");
            Assert.True(result == 2);

        }

        [Fact]
        public void Test_PdfPageCountValid()
        {
            // pdf_page_count: page count of a multi-page PDF
            var result = XbergConverter.PdfPageCount(System.IO.File.ReadAllBytes("pdf/sample_contract.pdf"), null);
            Assert.True(result == 10);

        }


    }
}
