// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b3427c1c59d7eebec947a099c1276d67b89511bd523e8603337d7473fc21b7f4
// To regenerate: alef e2e generate
// To verify freshness: alef verify

package io.xberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import io.xberg.Xberg;
import io.xberg.ExtractionConfig;
import java.util.Optional;
import io.xberg.JsonUtil;
import org.junit.jupiter.api.BeforeAll;

/** E2e tests for category: pdf. */
public class PdfTest {

    @BeforeAll
    static void initEnv() {
        if (System.getProperty("CRAWLBERG_ALLOW_PRIVATE_NETWORK") == null) {
            System.setProperty("CRAWLBERG_ALLOW_PRIVATE_NETWORK", "true");
        }
        if (System.getProperty("RUST_MIN_STACK") == null) {
            System.setProperty("RUST_MIN_STACK", "16777216");
        }
    }


    @Test
    void testPdfPageCountInvalid() throws Exception {
        // pdf_page_count: bytes that are not a PDF
        // Wrap setup_lines + call_expr inside the lambda so error fixtures
        // catch failures at *any* step — including `<Type>.fromJson(...)`
        // calls that throw on malformed JSON (e.g. error fixtures with an
        // invalid enum value like `"purpose":"invalid-purpose"`). Mirrors
        // the C# `Assert.ThrowsAnyAsync(() => client.X(Type.FromJson(...)))`
        // pattern.
        assertThrows(Exception.class, () -> {
            Xberg.pdfPageCount(java.nio.file.Files.readAllBytes(java.nio.file.Path.of("this is not a pdf document")), null);
        });

    }


    @Test
    void testPdfPageCountValid() throws Exception {
        // pdf_page_count: page count of a multi-page PDF
        var result = Xberg.pdfPageCount(java.nio.file.Files.readAllBytes(java.nio.file.Path.of("pdf/sample_contract.pdf")), null);
        assertEquals(10, result);


    }

}
