// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0a1f4aa6b3ae4db1921c7334ad8c2d9ee6b4feabb67f562ef0ad344ea6e51a77
// To regenerate: alef e2e generate
// To verify freshness: alef verify
//! E2e tests for category: pdf

use xberg::pdf_page_count;

#[test]
fn test_pdf_page_count_invalid() {
    // pdf_page_count: bytes that are not a PDF
    let pdf_bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../test_documents/this is not a pdf document"
    ))
    .expect("test_documents/this is not a pdf document must exist");
    let password: Option<String> = None;
    let result = pdf_page_count(&pdf_bytes, password.as_deref());
    assert!(result.is_err(), "expected call to fail");
}

#[test]
fn test_pdf_page_count_valid() {
    // pdf_page_count: page count of a multi-page PDF
    let pdf_bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../test_documents/pdf/sample_contract.pdf"
    ))
    .expect("test_documents/pdf/sample_contract.pdf must exist");
    let password: Option<String> = None;
    let result = pdf_page_count(&pdf_bytes, password.as_deref()).expect("call failed");
    assert_eq!(result, 10, "equals assertion failed");
}
