// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:aa9116e76b2fb83dea854d354076f6a7b900f53e3fc8615245f0ee1f0cf125f9
// To regenerate: alef e2e generate
// To verify freshness: alef verify
//! E2e tests for category: pdf

use xberg::pdf_page_count;

#[test]
fn test_pdf_page_count_invalid() {
    // pdf_page_count: a plain text file is not a PDF
    let pdf_bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../test_documents/text/plain.txt"
    ))
    .expect("test_documents/text/plain.txt must exist");
    let password: Option<String> = None;
    let result = pdf_page_count(&pdf_bytes, password.as_deref());
    assert!(result.is_err(), "expected call to fail");
}

#[test]
fn test_pdf_page_count_password() {
    // pdf_page_count: encrypted PDF opened with its user password
    let pdf_bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../test_documents/pdf/password_protected.pdf"
    ))
    .expect("test_documents/pdf/password_protected.pdf must exist");
    let password = Some(r#""#);
    let result = pdf_page_count(&pdf_bytes, password.as_deref()).expect("call failed");
    assert_eq!(result, 2, "equals assertion failed");
}

#[test]
fn test_pdf_page_count_valid() {
    // pdf_page_count: page count of a multi-page PDF
    let pdf_bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../test_documents/pdf/sample_contract.pdf"
    ))
    .expect("test_documents/pdf/sample_contract.pdf must exist");
    let password: Option<String> = None;
    let result = pdf_page_count(&pdf_bytes, password.as_deref()).expect("call failed");
    assert_eq!(result, 10, "equals assertion failed");
}
