# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0beb5677636293d2feae49f616057eda2f1c43e9380c71c529c25dc69a36db06
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.ExternalRedactionFinding do
  @moduledoc """
  One finding reported by an external content-inspection engine.

  Unknown fields are ignored, so an engine's raw output can be passed as is.
  Presidio's `entity_type` and AWS Comprehend's `Type`, `Text`,
  `BeginOffset`, `EndOffset` and `Score` are accepted as aliases.
  """

  @typedoc "One finding reported by an external content-inspection engine."
  @type t :: %__MODULE__{
          label: String.t() | nil,
          text: String.t() | nil,
          start: non_neg_integer() | nil,
          end: non_neg_integer() | nil,
          score: float() | nil
        }

  defstruct label: nil,
            text: nil,
            start: nil,
            end: nil,
            score: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
