# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:63f7ca5b0a4bbff9190c71454ed5baf3aa4aae4c1d7b9c94dcbe79ed235aac85
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.OcrConfig do
  @moduledoc "OCR configuration."

  @typedoc "OCR configuration."
  @type t :: %__MODULE__{
          enabled: boolean(),
          backend: String.t() | nil,
          language: [String.t()],
          tesseract_config: Xberg.TesseractConfig.t() | nil,
          output_format: Xberg.OutputFormat.t() | nil,
          paddle_ocr_config: Xberg.PaddleOcrConfig.t() | nil,
          backend_options: String.t() | nil,
          element_config: Xberg.OcrElementConfig.t() | nil,
          quality_thresholds: Xberg.OcrQualityThresholds.t() | nil,
          pipeline: Xberg.OcrPipelineConfig.t() | nil,
          auto_rotate: boolean(),
          vlm_fallback: Xberg.VlmFallbackPolicy.t(),
          vlm_config: Xberg.LlmConfig.t() | nil,
          vlm_prompt: String.t() | nil,
          acceleration: Xberg.AccelerationConfig.t() | nil,
          security_limits: Xberg.SecurityLimits.t() | nil,
          tessdata_bytes: map() | nil,
          tessdata_path: String.t() | nil,
          numeric_repair: boolean()
        }

  defstruct enabled: true,
            backend: "tesseract",
            language: ["eng"],
            tesseract_config: nil,
            output_format: nil,
            paddle_ocr_config: nil,
            backend_options: nil,
            element_config: nil,
            quality_thresholds: nil,
            pipeline: nil,
            auto_rotate: false,
            vlm_fallback: :disabled,
            vlm_config: nil,
            vlm_prompt: nil,
            acceleration: nil,
            security_limits: nil,
            tessdata_bytes: nil,
            tessdata_path: nil,
            numeric_repair: false

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
