# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d8c56d6f1784f4afbe246d89f0eb780113e31418e1db2e4c49b59e920c976b42
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.OcrPipelineStage do
  @moduledoc "A single backend stage in the OCR pipeline."

  @typedoc "A single backend stage in the OCR pipeline."
  @type t :: %__MODULE__{
          backend: String.t() | nil,
          priority: non_neg_integer(),
          language: [String.t()] | nil,
          tesseract_config: Xberg.TesseractConfig.t() | nil,
          paddle_ocr_config: Xberg.PaddleOcrConfig.t() | nil,
          vlm_config: Xberg.LlmConfig.t() | nil,
          backend_options: String.t() | nil
        }

  defstruct backend: nil,
            priority: 100,
            language: nil,
            tesseract_config: nil,
            paddle_ocr_config: nil,
            vlm_config: nil,
            backend_options: nil
end
