<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:cac86c036ba5ae33f791e3342f41501d677af61134cb5f098b3e1b4e4743edc3
// To regenerate: alef e2e generate
// To verify freshness: alef verify


declare(strict_types=1);

namespace Xberg\E2e;

use PHPUnit\Framework\TestCase;
use Xberg\XbergApi;
use Xberg\ExtractionConfig;

/** E2e tests for category: pdf. */
final class PdfTest extends TestCase
{


    /** pdf_page_count: bytes that are not a PDF */
    public function test_pdf_page_count_invalid(): void
    {
        $this->expectException(\Exception::class);
        $pdf_bytesBytes = file_get_contents("this is not a pdf document");
        if ($pdf_bytesBytes === false) { $this->fail("failed to read fixture: this is not a pdf document"); }
        XbergApi::pdfPageCount($pdf_bytesBytes);

    }


    /** pdf_page_count: page count of a multi-page PDF */
    public function test_pdf_page_count_valid(): void
    {
        $pdf_bytesBytes = file_get_contents("pdf/sample_contract.pdf");
        if ($pdf_bytesBytes === false) { $this->fail("failed to read fixture: pdf/sample_contract.pdf"); }
        $result = XbergApi::pdfPageCount($pdf_bytesBytes);

            $this->assertEquals(10, $result);


    }

}
