<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2389cd59ced41c0fe1640e36abe2388e2ed73cec3816e65d290cdd56e431ca33
// To regenerate: alef e2e generate
// To verify freshness: alef verify


declare(strict_types=1);

namespace Xberg\E2e;

use PHPUnit\Framework\TestCase;
use Xberg\XbergApi;
use Xberg\ExtractionConfig;

/** E2e tests for category: pdf. */
final class PdfTest extends TestCase
{


    /** pdf_page_count: a plain text file is not a PDF */
    public function test_pdf_page_count_invalid(): void
    {
        $this->expectException(\Exception::class);
        $pdf_bytesBytes = file_get_contents("text/plain.txt");
        if ($pdf_bytesBytes === false) { $this->fail("failed to read fixture: text/plain.txt"); }
        XbergApi::pdfPageCount($pdf_bytesBytes);

    }


    /** pdf_page_count: encrypted PDF opened with its user password */
    public function test_pdf_page_count_password(): void
    {
        $pdf_bytesBytes = file_get_contents("pdf/password_protected.pdf");
        if ($pdf_bytesBytes === false) { $this->fail("failed to read fixture: pdf/password_protected.pdf"); }
        $result = XbergApi::pdfPageCount($pdf_bytesBytes, "");

            $this->assertEquals(2, $result);


    }


    /** pdf_page_count: page count of a multi-page PDF */
    public function test_pdf_page_count_valid(): void
    {
        $pdf_bytesBytes = file_get_contents("pdf/sample_contract.pdf");
        if ($pdf_bytesBytes === false) { $this->fail("failed to read fixture: pdf/sample_contract.pdf"); }
        $result = XbergApi::pdfPageCount($pdf_bytesBytes);

            $this->assertEquals(10, $result);


    }

}
