// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:cb8b6f18c28630a34b110f16bf64ea75abd8b8c886b5ace0e4ac4ead5b8610bd
// To regenerate: alef e2e generate
// To verify freshness: alef verify
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import Xberg
import RustBridge

/// E2e tests for category: pdf.
final class PdfTests: XCTestCase {
    override class func setUp() {
        super.setUp()
        _ = "true".withCString { val in
            "CRAWLBERG_ALLOW_PRIVATE_NETWORK".withCString { key in
                setenv(key, val, 0)
            }
        }
        _ = "16777216".withCString { val in
            "RUST_MIN_STACK".withCString { key in
                setenv(key, val, 0)
            }
        }
        let _testDocs = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent() // <Module>Tests/
            .deletingLastPathComponent() // Tests/
            .deletingLastPathComponent() // swift_e2e/
            .deletingLastPathComponent() // e2e/
            .deletingLastPathComponent() // <repo root>
            .appendingPathComponent("test_documents")
        if FileManager.default.fileExists(atPath: _testDocs.path) {
            FileManager.default.changeCurrentDirectoryPath(_testDocs.path)
        }
    }

    func testPdfPageCountInvalid() throws {
        // pdf_page_count: bytes that are not a PDF
        do {
            let pdfBytesData = try Data(contentsOf: URL(fileURLWithPath: "this is not a pdf document"))
            let pdfBytesBytes = Array(pdfBytesData)
            _ = try Xberg.pdfPageCount(pdfBytes: pdfBytesBytes)
            XCTFail("expected to throw")
        } catch {
            // success
        }
    }

    func testPdfPageCountValid() throws {
        // pdf_page_count: page count of a multi-page PDF
        let pdfBytesData = try Data(contentsOf: URL(fileURLWithPath: "pdf/sample_contract.pdf"))
        let pdfBytesBytes = Array(pdfBytesData)
        let result = try Xberg.pdfPageCount(pdfBytes: pdfBytesBytes)
        // not_error: covered by try propagation
        XCTAssertEqual(result, 10)
    }

}
