// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:65588fee949c6eb2155e8cbf4773f7c855da033aac4f5405dfc360fa6990a805
// To regenerate: alef generate
// To verify freshness: alef verify
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Xberg;

/// <summary>
/// One finding reported by an external content-inspection engine.
///
/// Unknown fields are ignored, so an engine's raw output can be passed as is.
/// Presidio's `entity_type` and AWS Comprehend's `Type`, `Text`,
/// `BeginOffset`, `EndOffset` and `Score` are accepted as aliases.
/// </summary>
public sealed record ExternalRedactionFinding
{
    /// <summary>
    /// Engine category, surfaced as `PiiCategory.Custom(label)`.
    /// </summary>
    [JsonPropertyName("label")]
    public string Label { get; init; } = "";

    /// <summary>
    /// Literal value to redact. When absent, it is read from `content` at
    /// `start..end` under the requested `RedactionOffsetEncoding`.
    /// </summary>
    [JsonPropertyName("text")]
    public string? Text { get; init; } = null;

    /// <summary>
    /// Start offset (inclusive) into `content`.
    /// </summary>
    [JsonPropertyName("start")]
    public uint? Start { get; init; } = null;

    /// <summary>
    /// End offset (exclusive) into `content`.
    /// </summary>
    [JsonPropertyName("end")]
    public uint? End { get; init; } = null;

    /// <summary>
    /// Engine confidence in `[0.0, 1.0]`. Validated, not used for filtering.
    /// </summary>
    [JsonPropertyName("score")]
    public float? Score { get; init; } = null;


    /// <summary>
    /// Parse a <see cref="ExternalRedactionFinding"/> from a JSON string.
    /// </summary>
    /// <exception cref="XbergException">When the JSON cannot be deserialised.</exception>
    public static ExternalRedactionFinding FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<ExternalRedactionFinding>(json, JsonOptions)
                ?? throw new XbergException($"Failed to parse ExternalRedactionFinding from JSON: deserializer returned null");
        }
        catch (XbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new XbergException($"Failed to parse ExternalRedactionFinding from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower), new ByteArrayJsonConverter() },
    };

    /// <summary>Options for serializing config/input objects to FFI. Strips nulls
    /// (nullable C# fields default to null and would override required Rust fields with
    /// non-deserialisable nulls) but preserves explicit false/0 so caller intent is kept.</summary>
    private static readonly JsonSerializerOptions JsonSerializationOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower), new ByteArrayJsonConverter() },
    };
}
