// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:27d72da5385b9421ccfaaaae3f8e72573df90a43daf865128a56af0d6e119ba7
// To regenerate: alef e2e generate
// To verify freshness: alef verify
const std = @import("std");
const testing = std.testing;
const xberg = @import("xberg");

extern "c" fn setenv(name: [*:0]const u8, value: [*:0]const u8, overwrite: c_int) c_int;
fn allow_private_network() void {
    _ = setenv("CRAWLBERG_ALLOW_PRIVATE_NETWORK", "true", 1);
    _ = setenv("RUST_MIN_STACK", "16777216", 1);
}

// E2e tests for category: pdf

test "pdf_page_count_invalid" {
    // pdf_page_count: bytes that are not a PDF
    allow_private_network();
    var pdf_bytes_bytes_threaded = std.Io.Threaded.init(std.heap.c_allocator, .{});
    defer pdf_bytes_bytes_threaded.deinit();
    const pdf_bytes_bytes_io = pdf_bytes_bytes_threaded.io();
    const pdf_bytes_bytes = try std.Io.Dir.cwd().readFileAlloc(pdf_bytes_bytes_io, "this is not a pdf document", std.heap.c_allocator, .unlimited);
    defer std.heap.c_allocator.free(pdf_bytes_bytes);
    if (xberg.pdf_page_count(pdf_bytes_bytes, null)) |_| {
        return error.TestUnexpectedResult;
    } else |_| {}
}

test "pdf_page_count_valid" {
    // pdf_page_count: page count of a multi-page PDF
    allow_private_network();
    var pdf_bytes_bytes_threaded = std.Io.Threaded.init(std.heap.c_allocator, .{});
    defer pdf_bytes_bytes_threaded.deinit();
    const pdf_bytes_bytes_io = pdf_bytes_bytes_threaded.io();
    const pdf_bytes_bytes = try std.Io.Dir.cwd().readFileAlloc(pdf_bytes_bytes_io, "pdf/sample_contract.pdf", std.heap.c_allocator, .unlimited);
    defer std.heap.c_allocator.free(pdf_bytes_bytes);
    const result = try xberg.pdf_page_count(pdf_bytes_bytes, null);
    try testing.expectEqual(10, result);
}
