# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:75f2be2a8c1be94a15708b4367824d3c228e99c174be918c383bfea5f82a9540
# To regenerate: alef e2e generate
# To verify freshness: alef verify

"""E2e tests for category: pdf."""

from pathlib import Path

import pytest
from xberg import pdf_page_count


def test_pdf_page_count_invalid() -> None:
    """pdf_page_count: bytes that are not a PDF."""
    with pytest.raises(Exception):
        pdf_bytes = b"this is not a pdf document"
        pdf_page_count(pdf_bytes)


def test_pdf_page_count_valid() -> None:
    """pdf_page_count: page count of a multi-page PDF."""
    pdf_bytes = Path("pdf/sample_contract.pdf").read_bytes()

    result = pdf_page_count(pdf_bytes)
    assert result == 10
