# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2be3698d77e61c060735347b43913e36e661033ab4c4b9e35bbf1a378c81e17c
# To regenerate: alef e2e generate
# To verify freshness: alef verify

"""E2e tests for category: pdf."""

from pathlib import Path

import pytest
from xberg import pdf_page_count


def test_pdf_page_count_invalid() -> None:
    """pdf_page_count: a plain text file is not a PDF."""
    with pytest.raises(Exception):
        pdf_bytes = Path("text/plain.txt").read_bytes()
        pdf_page_count(pdf_bytes)


def test_pdf_page_count_password() -> None:
    """pdf_page_count: encrypted PDF opened with its user password."""
    pdf_bytes = Path("pdf/password_protected.pdf").read_bytes()
    password = ""

    result = pdf_page_count(pdf_bytes, password)
    assert result == 2


def test_pdf_page_count_valid() -> None:
    """pdf_page_count: page count of a multi-page PDF."""
    pdf_bytes = Path("pdf/sample_contract.pdf").read_bytes()

    result = pdf_page_count(pdf_bytes)
    assert result == 10
