// Generated by alef. Do not edit by hand.
// alef:hash:1aa5df0c65f28c206fdbf54ad1b9e884b5ccc5b86923c466c01da1b220d03660
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/**
 * One finding reported by an external content-inspection engine.
 *
 * Unknown fields are ignored, so an engine's raw output can be passed as is.
 * Presidio's `entity_type` and AWS Comprehend's `Type`, `Text`,
 * `BeginOffset`, `EndOffset` and `Score` are accepted as aliases.
 */
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
data class ExternalRedactionFinding(
    /** Engine category, surfaced as `PiiCategory.Custom(label)`. */
    val label: String = "",
    /**
     * Literal value to redact. When absent, it is read from `content` at
     * `start..end` under the requested `RedactionOffsetEncoding`.
     */
    val text: String? = null,
    /** Start offset (inclusive) into `content`. */
    val start: Int? = null,
    /** End offset (exclusive) into `content`. */
    val end: Int? = null,
    /** Engine confidence in `[0.0, 1.0]`. Validated, not used for filtering. */
    val score: Float? = null,
)
