// Generated by alef. Do not edit by hand.
// alef:hash:0470cc395360b992873664e5c1186c25062d3cf4f2dc9c2caa5213e8497cba58
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/** A single backend stage in the OCR pipeline. */
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
data class OcrPipelineStage(
    /**
     * Backend name: "tesseract", "paddleocr", "paddle-ocr", "sceptre", "vlm", or a custom registered name.
     * Sceptre uses ONNX Runtime on desktop/server and tract on Android/iOS; browser WebAssembly has a separate
     * byte-fed engine because the normal async OCR registry assumes native model storage.
     */
    val backend: String,
    /** Priority weight (higher = tried first). Stages are sorted by priority descending. */
    val priority: Int = 100,
    /**
     * Language override for this stage (None = use parent OcrConfig.language).
     *
     * A list is the canonical form and the only form accepted by the binding
     * object APIs: `["eng", "deu"]`. When deserializing from a config file,
     * JSON body, or the REST/MCP API, a single string is also accepted,
     * either as one code ("eng") or "+"-joined ("eng+deu").
     */
    val language: List<String>? = null,
    /** Tesseract-specific config override for this stage. */
    val tesseractConfig: TesseractConfig? = null,
    /**
     * PaddleOCR-specific config for this stage.
     *
     * Unset fields keep their defaults. In a config file, a JSON config, or a REST or MCP request
     * body, an unknown key is a configuration error. A typed object built in a binding has only
     * the fields it declares, so it ignores any other property, as every other typed config does.
     */
    val paddleOcrConfig: PaddleOcrConfig? = null,
    /** VLM config override for this pipeline stage. */
    val vlmConfig: LlmConfig? = null,
    /**
     * Arbitrary per-call options passed through to the backend unchanged.
     *
     * Backends that support runtime tuning (mode switching, preprocessing
     * flags, inference parameters, etc.) read this value and deserialize
     * the keys they care about. Keys unknown to the backend are silently
     * ignored, so options from different backends can coexist in the same
     * config without conflict.
     *
     * Example (custom backend):
     * ```json
     * { "mode": "fast", "enable_layout": true }
     * ```
     */
    val backendOptions: Any? = null,
)
