// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7479b0c1386c4eadf53a106caec10cde112879677f64955218f40914859bf399
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * One finding reported by an external content-inspection engine.
 *
 * Unknown fields are ignored, so an engine's raw output can be passed as is.
 * Presidio's {@code entity_type} and AWS Comprehend's {@code Type}, {@code
 * Text},
 * {@code BeginOffset}, {@code EndOffset} and {@code Score} are accepted as
 * aliases.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ExternalRedactionFinding.Builder.class)
public record
ExternalRedactionFinding(@JsonProperty("label") String label,
                         @Nullable @JsonProperty("text") String text,
                         @Nullable @JsonProperty("start") Integer start,
                         @Nullable @JsonProperty("end") Integer end,
                         @Nullable @JsonProperty("score") Float score) {
  /** Creates a new Builder for constructing instances of this record. */
  public static Builder builder() { return new Builder(); }

  // CPD-OFF
  /** Jackson builder for ExternalRedactionFinding deserialization. */
  @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
  @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
  public static final class Builder {

    private String label;
    @Nullable private String text;
    @Nullable private Integer start;
    @Nullable private Integer end;
    @Nullable private Float score;

    /** Sets the label field. */
    @JsonProperty("label")
    public Builder withLabel(final String value) {
      this.label = value;
      return this;
    }

    /** Sets the text field. */
    @JsonProperty("text")
    public Builder withText(final @Nullable String value) {
      this.text = value;
      return this;
    }

    /** Sets the start field. */
    @JsonProperty("start")
    public Builder withStart(final @Nullable Integer value) {
      this.start = value;
      return this;
    }

    /** Sets the end field. */
    @JsonProperty("end")
    public Builder withEnd(final @Nullable Integer value) {
      this.end = value;
      return this;
    }

    /** Sets the score field. */
    @JsonProperty("score")
    public Builder withScore(final @Nullable Float value) {
      this.score = value;
      return this;
    }

    /**
     * Constructs a ExternalRedactionFinding instance from the builder's
     * current state.
     */
    public ExternalRedactionFinding build() {
      return new ExternalRedactionFinding(label, text, start, end, score);
    }
  }
  // CPD-ON
}
