# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:26f6ef11b21a8061bb2511f721532e40c289475c23cb0d06761d02fe44173549
# To regenerate: alef e2e generate
# To verify freshness: alef verify
# frozen_string_literal: true

require 'spec_helper'
require 'xberg'
require 'json'

RSpec.describe 'pdf' do

  it 'pdf_page_count_invalid: pdf_page_count: bytes that are not a PDF' do
    expect {
      pdf_bytes = 'this is not a pdf document'.b.bytes
      Xberg.pdf_page_count(pdf_bytes)
    }.to raise_error(RuntimeError)
  end


  it 'pdf_page_count_valid: pdf_page_count: page count of a multi-page PDF' do
    pdf_bytes = File.read("pdf/sample_contract.pdf").bytes
    result = Xberg.pdf_page_count(pdf_bytes)
    expect(result).to eq(10)

  end

end
