# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f8087ae7b7ecdb0888103609058fd61045a8c4fef2186174178a5ad2cc95cf6f
# To regenerate: alef e2e generate
# To verify freshness: alef verify
# frozen_string_literal: true

require 'spec_helper'
require 'xberg'
require 'json'

RSpec.describe 'pdf' do

  it 'pdf_page_count_invalid: pdf_page_count: a plain text file is not a PDF' do
    expect {
      pdf_bytes = File.read("text/plain.txt").bytes
      Xberg.pdf_page_count(pdf_bytes)
    }.to raise_error(RuntimeError)
  end


  it 'pdf_page_count_password: pdf_page_count: encrypted PDF opened with its user password' do
    pdf_bytes = File.read("pdf/password_protected.pdf").bytes
    result = Xberg.pdf_page_count(pdf_bytes, '')
    expect(result).to eq(2)

  end


  it 'pdf_page_count_valid: pdf_page_count: page count of a multi-page PDF' do
    pdf_bytes = File.read("pdf/sample_contract.pdf").bytes
    result = Xberg.pdf_page_count(pdf_bytes)
    expect(result).to eq(10)

  end

end
