// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6d10a672dd3a16e34a8aed36099e9077252949963e3902d7b072e43cb0f0f638
// To regenerate: alef e2e generate
// To verify freshness: alef verify
// ignore_for_file: unused_local_variable, unused_element

import 'package:test/test.dart';
import 'dart:io';
import 'package:xberg/xberg.dart';
import 'package:xberg/src/xberg_bridge_generated/frb_generated.dart'
    show RustLib;
import 'dart:ffi';
import 'package:ffi/ffi.dart';

// E2e tests for category: pdf

void _setEnv(String key, String value) {
  final libc = DynamicLibrary.process();
  final setenv = libc
      .lookupFunction<
        Int32 Function(Pointer<Utf8>, Pointer<Utf8>, Int32),
        int Function(Pointer<Utf8>, Pointer<Utf8>, int)
      >('setenv');
  final keyPtr = key.toNativeUtf8();
  final valuePtr = value.toNativeUtf8();
  try {
    final result = setenv(keyPtr, valuePtr, 1);
    if (result != 0) {
      throw StateError(
        'setenv failed for ${key}=${value} with return code $result',
      );
    }
  } finally {
    calloc.free(keyPtr);
    calloc.free(valuePtr);
  }
}

void main() {
  var _rustLibInitialized = false;
  String? _originalCwd;

  setUpAll(() async {
    _setEnv('CRAWLBERG_ALLOW_PRIVATE_NETWORK', 'true');
    _setEnv('RUST_MIN_STACK', '16777216');
    await RustLib.init();
    _rustLibInitialized = true;
    _originalCwd = Directory.current.path;
    final _testDocs =
        Platform.environment['FIXTURES_DIR'] ?? '../../test_documents';
    final _dir = Directory(_testDocs);
    if (_dir.existsSync()) Directory.current = _dir;
  });

  tearDownAll(() async {
    if (_rustLibInitialized) {
      RustLib.dispose();
    }
    final _cwd = _originalCwd;
    if (_cwd != null) Directory.current = _cwd;
  });

  test('pdf_page_count: bytes that are not a PDF', () async {
    await expectLater(
      XbergBridge.pdfPageCount(
        File('this is not a pdf document').readAsBytesSync(),
      ),
      throwsA(anything),
    );
  });

  test('pdf_page_count: page count of a multi-page PDF', () async {
    final result = await XbergBridge.pdfPageCount(
      File('pdf/sample_contract.pdf').readAsBytesSync(),
    );
    expect(result, equals(10));
  });
}
