// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3f533285fca61a6f7c7b106e6494d376e9268dbbea81664bb04a7fbefc3f0f08
// To regenerate: alef e2e generate
// To verify freshness: alef verify

// E2e tests for category: pdf
package e2e_test

import (
	"os"
	"testing"

	xberg "github.com/xberg-io/xberg/packages/go"
)

func Test_PdfPageCountInvalid(t *testing.T) {
	// pdf_page_count: bytes that are not a PDF
	pdf_bytesBytes, pdf_bytesBytesErr := os.ReadFile(`this is not a pdf document`)
	if pdf_bytesBytesErr != nil {
		t.Fatalf("read fixture this is not a pdf document: %v", pdf_bytesBytesErr)
	}
	_, err := xberg.PdfPageCount(pdf_bytesBytes, nil)
	if err == nil {
		t.Errorf("expected an error, but call succeeded")
	}
}

func Test_PdfPageCountValid(t *testing.T) {
	// pdf_page_count: page count of a multi-page PDF
	pdf_bytesBytes, pdf_bytesBytesErr := os.ReadFile(`pdf/sample_contract.pdf`)
	if pdf_bytesBytesErr != nil {
		t.Fatalf("read fixture pdf/sample_contract.pdf: %v", pdf_bytesBytesErr)
	}
	result, err := xberg.PdfPageCount(pdf_bytesBytes, nil)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result == nil {
		t.Fatalf("expected non-nil result")
	}
	value := *result
	if value != 10 {
		t.Errorf("equals mismatch: got %v", value)
	}
}
